# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Pyqt5 project\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1118, 521)
        self.pushButton_Load_control = QtWidgets.QPushButton(Dialog)
        self.pushButton_Load_control.setGeometry(QtCore.QRect(830, 410, 31, 31))
        self.pushButton_Load_control.setObjectName("pushButton_Load_control")
        self.pushButton_simulate = QtWidgets.QPushButton(Dialog)
        self.pushButton_simulate.setGeometry(QtCore.QRect(520, 470, 91, 41))
        self.pushButton_simulate.setObjectName("pushButton_simulate")
        self.pushButton_Motor = QtWidgets.QPushButton(Dialog)
        self.pushButton_Motor.setGeometry(QtCore.QRect(100, 10, 31, 31))
        self.pushButton_Motor.setObjectName("pushButton_Motor")
        self.pushButton_Shaft = QtWidgets.QPushButton(Dialog)
        self.pushButton_Shaft.setGeometry(QtCore.QRect(190, 410, 31, 31))
        self.pushButton_Shaft.setObjectName("pushButton_Shaft")
        self.pushButton_shaftspeed_control = QtWidgets.QPushButton(Dialog)
        self.pushButton_shaftspeed_control.setGeometry(QtCore.QRect(30, 360, 31, 31))
        self.pushButton_shaftspeed_control.setObjectName("pushButton_shaftspeed_control")
        self.pushButton_Testbearing = QtWidgets.QPushButton(Dialog)
        self.pushButton_Testbearing.setGeometry(QtCore.QRect(510, 80, 31, 31))
        self.pushButton_Testbearing.setObjectName("pushButton_Testbearing")
        self.pushButton_Load = QtWidgets.QPushButton(Dialog)
        self.pushButton_Load.setGeometry(QtCore.QRect(740, 20, 31, 31))
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.pushButton_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_back.setGeometry(QtCore.QRect(680, 470, 91, 41))
        self.pushButton_back.setObjectName("pushButton_back")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-60, -20, 1271, 541))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./picture/123.png"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton_Load_control.raise_()
        self.pushButton_simulate.raise_()
        self.pushButton_Motor.raise_()
        self.pushButton_Shaft.raise_()
        self.pushButton_shaftspeed_control.raise_()
        self.pushButton_Testbearing.raise_()
        self.pushButton_Load.raise_()
        self.pushButton_back.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Virtual bearing test beach"))
        self.pushButton_Load_control.setText(_translate("Dialog", "6"))
        self.pushButton_simulate.setText(_translate("Dialog", "Simulate"))
        self.pushButton_Motor.setText(_translate("Dialog", "1"))
        self.pushButton_Shaft.setText(_translate("Dialog", "2"))
        self.pushButton_shaftspeed_control.setText(_translate("Dialog", "5"))
        self.pushButton_Testbearing.setText(_translate("Dialog", "4"))
        self.pushButton_Load.setText(_translate("Dialog", "3"))
        self.pushButton_back.setText(_translate("Dialog", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Main()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
